environment:
    global:
      PYTHON: "C:\\Python36"

    matrix:
        - TOXENV: py27-pip8.1.1

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - pip install tox

build: false

test_script:
    - tox
