environment:
    global:
      PYTHON: "C:\\Python36"

    matrix:
        - TOXENV: py35-pip8.1.1
          PIP: 8.1.1

        - TOXENV: py36-pip9.0.1
          PIP: 9.0.1

        - TOXENV: py37-pip19.0.3
          PIP: 19.0.3

matrix:
  allow_failures:
    - PIP: master

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - pip install tox

build: false

test_script:
    - tox -- -k test_diff_with_editable

after_test:
  # Add tox environment to PATH.
  - "SET PATH=%CD%\\.tox\\%TOXENV%\\scripts;%PATH%"
  - IF NOT "x%TOXENV:-coverage=%"=="x%TOXENV%" (
      pip install codecov &&
      coverage xml &&
      appveyor-retry codecov --required -X gcov pycov search -f coverage.xml -n %TOXENV%-windows
    )
