environment:
    global:
      PYTHON: "C:\\Python36"

    matrix:
        - TOXENV: py27-coverage
        - TOXENV: py37-coverage
        - TOXENV: py35
        - TOXENV: py36

matrix:
  fast_finish: true

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - pip install tox

build: false

test_script:
    - tox

after_test:
  # Add tox environment to PATH.
  - "SET PATH=%CD%\\.tox\\%TOXENV%\\scripts;%PATH%"
  - IF NOT "x%TOXENV:-coverage=%"=="x%TOXENV%" (
      pip install codecov &&
      coverage xml &&
      codecov --required -X gcov pycov search -f coverage.xml -n %TOXENV%-windows
    )
