environment:

    matrix:
        - TOXENV: py37-piplatest
          PIP: latest

matrix:
  allow_failures:
    - PIP: master

install:
    - C:\Python36\python -m pip install tox

build: false

test_script:
    - C:\Python36\Scripts\tox
