environment:
    global:
      PYTHON: "C:\\Python36"

    matrix:
        - TOXENV: checkqa

matrix:
  fast_finish: true
  allow_failures:
    - PIP: master
    - PIP: 19.3  # TODO remove after pip==19.3 being released

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - pip install tox

build: false

test_script:
    - tox

after_test:
  # Add tox environment to PATH.
  - "SET PATH=%CD%\\.tox\\%TOXENV%\\scripts;%PATH%"
  - IF NOT "x%TOXENV:-coverage=%"=="x%TOXENV%" (
      pip install codecov &&
      coverage xml &&
      appveyor-retry codecov --required -X gcov pycov search -f coverage.xml -n %TOXENV%-windows
    )
