dist: xenial
sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"

install:
  - travis_retry pip install tox-travis
script:
  - tox

stages:
- baseline
- test
- name: deploy
  if: repo = jazzband/pip-tools AND tag IS present

jobs:
  exclude:
    # Baseline jobs (included there/below).
    - python: "2.7"
    - python: "3.7"

  include:
    # Baseline stage to abort early.
    - stage: baseline
      python: "2.7"
    - python: "3.7"

    # QA checks.
    - stage: baseline
      env: TOXENV=checkqa
      python: 3.7
      after_success: skip  # No need coverage
      cache:
        directories:
          - $HOME/.cache/pre-commit
    - env: TOXENV=readme
      python: 3.7
      after_success: skip  # No need coverage

    - stage: deploy
      install: skip  # No need to install tox-travis on deploy.
      script: skip  # No test on the deploy stage.
      python: 2.7
      env: skip  # No special env required.
      after_success: true  # No need coverage
      deploy:
        provider: pypi
        user: jazzband
        server: https://jazzband.co/projects/pip-tools/upload
        distributions: sdist bdist_wheel
        password:
          secure: TCG9beQgarL/EDHiwSCgEf1JnofTroA5QRp2OTL3QC+eaar6FftqxcJQw3FwnHJ7NarI6E7bcxn9wDRs6tXqiLcyGOzWUnR4jQ94w/7YaLQjzLr8g1toRnb9dNwU1l14z2hmnzc4oRqu7+pi4wIpBx+11Ke9JXNcrC+cRFwCdLQ=
        on:
          tags: true
          repo: jazzband/pip-tools
  allow_failures:
    - python: 3.8-dev

after_success:
  - travis_retry pip install codecov coveralls
  - codecov -n "py${TRAVIS_PYTHON_VERSION}-pip${PIP}-${TRAVIS_OS_NAME}"
  - "COVERALLS_PARALLEL=true coveralls"

notifications:
  webhooks: https://coveralls.io/webhook
