dist: xenial
sudo: false
language: python
python:
  - "2.7"
  - "3.7"

env:
  - PIP=18.0

cache: pip
install:
  - travis_retry pip install tox-travis codecov
script:
  - tox
after_success: codecov -e PIP
