name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
  schedule:
    # Run everyday at 03:53 UTC
    - cron: 53 3 * * *

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.python-version }} / ${{ matrix.pip-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - Ubuntu
          - Windows
          - MacOS
        python-version:
          - 3.8
          - 2.7
          - pypy3
          - 3.5
          - 3.6
          - 3.7
          - pypy2
        pip-version:
          - "latest"
          - "20.0"
        # Test pypy only with the latest pip version to reduce the number of jobs
        exclude:
          - pip-version: "20.0"
            python-version: pypy2
          - pip-version: "20.0"
            python-version: pypy3
          # TODO: fix test_realistic_complex_sub_dependencies test
          #       and remove Windows exclusion
          - os: Windows
            python-version: pypy2
          - os: Windows
            python-version: pypy3

    env:
      PY_COLORS: 1
      TOXENV: pip${{ matrix.pip-version }}-coverage
      TOX_PARALLEL_NO_SPINNER: 1
    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Prepare test environment
        run: tox --notest -p auto --parallel-live
      - name: Test pip ${{ matrix.pip-version }}
        run: tox
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.6
        with:
          file: ./coverage.xml
          name: ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.pip-version }}
